export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      early_access: {
        Row: {
          created_at: string;
          email: string;
          id: number;
        };
        Insert: {
          created_at?: string;
          email: string;
          id?: number;
        };
        Update: {
          created_at?: string;
          email?: string;
          id?: number;
        };
        Relationships: [];
      };
      metric_data: {
        Row: {
          created_at: string;
          crux_cls_avg: number | null;
          crux_cls_good: number | null;
          crux_cls_p75: number | null;
          crux_cls_poor: number | null;
          crux_inp_avg: number | null;
          crux_inp_good: number | null;
          crux_inp_p75: number | null;
          crux_inp_poor: number | null;
          crux_lcp_avg: number | null;
          crux_lcp_good: number | null;
          crux_lcp_p75: number | null;
          crux_lcp_poor: number | null;
          cumulative_layout_shift: number | null;
          device_type: string;
          first_contentful_paint: number | null;
          firstinputdelay: number | null;
          interactiontonextpaint: number | null;
          largest_contentful_paint: number | null;
          lcpasset: string | null;
          lcpassetsize: number | null;
          pageloadtime: number | null;
          performance_score: number | null;
          record_id: string;
          server_response_time: number | null;
          speed_index: number | null;
          status: string | null;
          total_blocking_time: number | null;
          totalloadtime: number | null;
          website_name: string | null;
        };
        Insert: {
          created_at: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          cumulative_layout_shift?: number | null;
          device_type: string;
          first_contentful_paint?: number | null;
          firstinputdelay?: number | null;
          interactiontonextpaint?: number | null;
          largest_contentful_paint?: number | null;
          lcpasset?: string | null;
          lcpassetsize?: number | null;
          pageloadtime?: number | null;
          performance_score?: number | null;
          record_id?: string;
          server_response_time?: number | null;
          speed_index?: number | null;
          status?: string | null;
          total_blocking_time?: number | null;
          totalloadtime?: number | null;
          website_name?: string | null;
        };
        Update: {
          created_at?: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          cumulative_layout_shift?: number | null;
          device_type?: string;
          first_contentful_paint?: number | null;
          firstinputdelay?: number | null;
          interactiontonextpaint?: number | null;
          largest_contentful_paint?: number | null;
          lcpasset?: string | null;
          lcpassetsize?: number | null;
          pageloadtime?: number | null;
          performance_score?: number | null;
          record_id?: string;
          server_response_time?: number | null;
          speed_index?: number | null;
          status?: string | null;
          total_blocking_time?: number | null;
          totalloadtime?: number | null;
          website_name?: string | null;
        };
        Relationships: [];
      };
      metric_data_desktop: {
        Row: {
          created_at: string;
          crux_cls_avg: number | null;
          crux_cls_good: number | null;
          crux_cls_p75: number | null;
          crux_cls_poor: number | null;
          crux_inp_avg: number | null;
          crux_inp_good: number | null;
          crux_inp_p75: number | null;
          crux_inp_poor: number | null;
          crux_lcp_avg: number | null;
          crux_lcp_good: number | null;
          crux_lcp_p75: number | null;
          crux_lcp_poor: number | null;
          cumulative_layout_shift: number | null;
          device_type: string;
          first_contentful_paint: number | null;
          firstinputdelay: number | null;
          interactiontonextpaint: number | null;
          largest_contentful_paint: number | null;
          lcpasset: string | null;
          lcpassetsize: number | null;
          pageloadtime: number | null;
          performance_score: number | null;
          record_id: string;
          server_response_time: number | null;
          speed_index: number | null;
          status: string | null;
          total_blocking_time: number | null;
          totalloadtime: number | null;
          website_name: string | null;
        };
        Insert: {
          created_at: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          cumulative_layout_shift?: number | null;
          device_type: string;
          first_contentful_paint?: number | null;
          firstinputdelay?: number | null;
          interactiontonextpaint?: number | null;
          largest_contentful_paint?: number | null;
          lcpasset?: string | null;
          lcpassetsize?: number | null;
          pageloadtime?: number | null;
          performance_score?: number | null;
          record_id?: string;
          server_response_time?: number | null;
          speed_index?: number | null;
          status?: string | null;
          total_blocking_time?: number | null;
          totalloadtime?: number | null;
          website_name?: string | null;
        };
        Update: {
          created_at?: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          cumulative_layout_shift?: number | null;
          device_type?: string;
          first_contentful_paint?: number | null;
          firstinputdelay?: number | null;
          interactiontonextpaint?: number | null;
          largest_contentful_paint?: number | null;
          lcpasset?: string | null;
          lcpassetsize?: number | null;
          pageloadtime?: number | null;
          performance_score?: number | null;
          record_id?: string;
          server_response_time?: number | null;
          speed_index?: number | null;
          status?: string | null;
          total_blocking_time?: number | null;
          totalloadtime?: number | null;
          website_name?: string | null;
        };
        Relationships: [];
      };
      metric_data_mobile: {
        Row: {
          created_at: string;
          crux_cls_avg: number | null;
          crux_cls_good: number | null;
          crux_cls_p75: number | null;
          crux_cls_poor: number | null;
          crux_inp_avg: number | null;
          crux_inp_good: number | null;
          crux_inp_p75: number | null;
          crux_inp_poor: number | null;
          crux_lcp_avg: number | null;
          crux_lcp_good: number | null;
          crux_lcp_p75: number | null;
          crux_lcp_poor: number | null;
          cumulative_layout_shift: number | null;
          device_type: string;
          first_contentful_paint: number | null;
          firstinputdelay: number | null;
          interactiontonextpaint: number | null;
          largest_contentful_paint: number | null;
          lcpasset: string | null;
          lcpassetsize: number | null;
          pageloadtime: number | null;
          performance_score: number | null;
          record_id: string;
          server_response_time: number | null;
          speed_index: number | null;
          status: string | null;
          total_blocking_time: number | null;
          totalloadtime: number | null;
          website_name: string | null;
        };
        Insert: {
          created_at: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          cumulative_layout_shift?: number | null;
          device_type: string;
          first_contentful_paint?: number | null;
          firstinputdelay?: number | null;
          interactiontonextpaint?: number | null;
          largest_contentful_paint?: number | null;
          lcpasset?: string | null;
          lcpassetsize?: number | null;
          pageloadtime?: number | null;
          performance_score?: number | null;
          record_id?: string;
          server_response_time?: number | null;
          speed_index?: number | null;
          status?: string | null;
          total_blocking_time?: number | null;
          totalloadtime?: number | null;
          website_name?: string | null;
        };
        Update: {
          created_at?: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          cumulative_layout_shift?: number | null;
          device_type?: string;
          first_contentful_paint?: number | null;
          firstinputdelay?: number | null;
          interactiontonextpaint?: number | null;
          largest_contentful_paint?: number | null;
          lcpasset?: string | null;
          lcpassetsize?: number | null;
          pageloadtime?: number | null;
          performance_score?: number | null;
          record_id?: string;
          server_response_time?: number | null;
          speed_index?: number | null;
          status?: string | null;
          total_blocking_time?: number | null;
          totalloadtime?: number | null;
          website_name?: string | null;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          allowSpeedySite: boolean;
          cruxData: boolean;
          dailyMonitoring: boolean;
          favicon_file: string | null;
          order_date: string;
          order_id: string;
          order_status: boolean;
          page_tracking: number | null;
          performanceWarning: boolean;
          rank: number | null;
          user_email: string;
          website_address: string;
          website_name: string;
        };
        Insert: {
          allowSpeedySite: boolean;
          cruxData: boolean;
          dailyMonitoring: boolean;
          favicon_file?: string | null;
          order_date?: string;
          order_id?: string;
          order_status: boolean;
          page_tracking?: number | null;
          performanceWarning: boolean;
          rank?: number | null;
          user_email: string;
          website_address: string;
          website_name: string;
        };
        Update: {
          allowSpeedySite?: boolean;
          cruxData?: boolean;
          dailyMonitoring?: boolean;
          favicon_file?: string | null;
          order_date?: string;
          order_id?: string;
          order_status?: boolean;
          page_tracking?: number | null;
          performanceWarning?: boolean;
          rank?: number | null;
          user_email?: string;
          website_address?: string;
          website_name?: string;
        };
        Relationships: [
          {
            foreignKeyName: "orders_user_email_fkey";
            columns: ["user_email"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["email"];
          },
        ];
      };
      page_monitoring: {
        Row: {
          created_at: string;
          page_id: string;
          url: string;
          website: string;
        };
        Insert: {
          created_at?: string;
          page_id?: string;
          url: string;
          website: string;
        };
        Update: {
          created_at?: string;
          page_id?: string;
          url?: string;
          website?: string;
        };
        Relationships: [
          {
            foreignKeyName: "page_monitoring_website_fkey";
            columns: ["website"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["website_name"];
          },
        ];
      };
      pageperf_data: {
        Row: {
          browser: string | null;
          browser_version: string | null;
          cookies_count: number | null;
          created_at: string;
          crux_cls_avg: number | null;
          crux_cls_good: number | null;
          crux_cls_p75: number | null;
          crux_cls_poor: number | null;
          crux_fcp_avg: number | null;
          crux_fcp_good: number | null;
          crux_fcp_p75: number | null;
          crux_fcp_poor: number | null;
          crux_inp_avg: number | null;
          crux_inp_good: number | null;
          crux_inp_p75: number | null;
          crux_inp_poor: number | null;
          crux_lcp_avg: number | null;
          crux_lcp_good: number | null;
          crux_lcp_p75: number | null;
          crux_lcp_poor: number | null;
          crux_ttfb_avg: number | null;
          crux_ttfb_good: number | null;
          crux_ttfb_p75: number | null;
          crux_ttfb_poor: number | null;
          device_type: string;
          document_decodedbody_size: number | null;
          document_encodedbody_size: number | null;
          document_timing: Json | null;
          document_transfersize: number | null;
          documentheight: number | null;
          documenttitle: string | null;
          dom_complete_max: number | null;
          dom_complete_mean: number | null;
          dom_complete_min: number | null;
          dom_elements_max: number | null;
          dom_elements_mean: number | null;
          dom_elements_min: number | null;
          dom_interactive_max: number | null;
          dom_interactive_mean: number | null;
          dom_interactive_min: number | null;
          domains: Json | null;
          inp_eventtime_max: number | null;
          inp_eventtime_mean: number | null;
          inp_eventtime_min: number | null;
          inp_latency_max: number | null;
          inp_latency_mean: number | null;
          inp_latency_min: number | null;
          lab_cls_max: number | null;
          lab_cls_mean: number | null;
          lab_cls_min: number | null;
          lab_contentsize: number | null;
          lab_css_contentsize_max: number | null;
          lab_css_contentsize_mean: number | null;
          lab_css_contentsize_min: number | null;
          lab_css_request_count_max: number | null;
          lab_css_request_count_mean: number | null;
          lab_css_request_count_min: number | null;
          lab_css_transfersize_max: number | null;
          lab_css_transfersize_mean: number | null;
          lab_css_transfersize_min: number | null;
          lab_domain_lookup: number | null;
          lab_error_max: number | null;
          lab_error_mean: number | null;
          lab_error_min: number | null;
          lab_fcp_max: number | null;
          lab_fcp_mean: number | null;
          lab_fcp_min: number | null;
          lab_fid_max: number | null;
          lab_fid_mean: number | null;
          lab_fid_min: number | null;
          lab_firstmeaningfulpaint_max: number | null;
          lab_firstmeaningfulpaint_mean: number | null;
          lab_firstmeaningfulpaint_min: number | null;
          lab_font_contentsize_max: number | null;
          lab_font_contentsize_mean: number | null;
          lab_font_contentsize_min: number | null;
          lab_font_request_count_max: number | null;
          lab_font_request_count_mean: number | null;
          lab_font_request_count_min: number | null;
          lab_font_transfersize_max: number | null;
          lab_font_transfersize_mean: number | null;
          lab_font_transfersize_min: number | null;
          lab_fullyloaded_max: number | null;
          lab_fullyloaded_mean: number | null;
          lab_fullyloaded_min: number | null;
          lab_html_contentsize_max: number | null;
          lab_html_contentsize_mean: number | null;
          lab_html_contentsize_min: number | null;
          lab_html_request_count_max: number | null;
          lab_html_request_count_mean: number | null;
          lab_html_request_count_min: number | null;
          lab_html_transfersize_max: number | null;
          lab_html_transfersize_mean: number | null;
          lab_html_transfersize_min: number | null;
          lab_image_contentsize_max: number | null;
          lab_image_contentsize_mean: number | null;
          lab_image_contentsize_min: number | null;
          lab_image_request_count_max: number | null;
          lab_image_request_count_mean: number | null;
          lab_image_request_count_min: number | null;
          lab_image_transfersize_max: number | null;
          lab_image_transfersize_mean: number | null;
          lab_image_transfersize_min: number | null;
          lab_js_contentsize_max: number | null;
          lab_js_contentsize_mean: number | null;
          lab_js_contentsize_min: number | null;
          lab_js_request_count_max: number | null;
          lab_js_request_count_mean: number | null;
          lab_js_request_count_min: number | null;
          lab_js_transfersize_max: number | null;
          lab_js_transfersize_mean: number | null;
          lab_js_transfersize_min: number | null;
          lab_json_contentsize_max: number | null;
          lab_json_contentsize_mean: number | null;
          lab_json_contentsize_min: number | null;
          lab_json_request_count_max: number | null;
          lab_json_request_count_mean: number | null;
          lab_json_request_count_min: number | null;
          lab_json_transfersize_max: number | null;
          lab_json_transfersize_mean: number | null;
          lab_json_transfersize_min: number | null;
          lab_lcp_max: number | null;
          lab_lcp_mean: number | null;
          lab_lcp_min: number | null;
          lab_speed_index_max: number | null;
          lab_speed_index_mean: number | null;
          lab_speed_index_min: number | null;
          lab_srt_max: number | null;
          lab_srt_mean: number | null;
          lab_srt_min: number | null;
          lab_svg_contentsize_max: number | null;
          lab_svg_contentsize_mean: number | null;
          lab_svg_contentsize_min: number | null;
          lab_svg_request_count_max: number | null;
          lab_svg_request_count_mean: number | null;
          lab_svg_request_count_min: number | null;
          lab_svg_transfersize_max: number | null;
          lab_svg_transfersize_mean: number | null;
          lab_svg_transfersize_min: number | null;
          lab_tbt_max: number | null;
          lab_tbt_mean: number | null;
          lab_tbt_min: number | null;
          lab_total_contentsize_max: number | null;
          lab_total_contentsize_mean: number | null;
          lab_total_contentsize_min: number | null;
          lab_total_requests_max: number | null;
          lab_total_requests_mean: number | null;
          lab_total_requests_min: number | null;
          lab_total_transfersize_max: number | null;
          lab_total_transfersize_mean: number | null;
          lab_total_transfersize_min: number | null;
          lab_ttfb_max: number | null;
          lab_ttfb_mean: number | null;
          lab_ttfb_min: number | null;
          last_visual_change_max: number | null;
          last_visual_change_mean: number | null;
          last_visual_change_min: number | null;
          lcp_element_size_max: number | null;
          lcp_element_size_mean: number | null;
          lcp_element_size_min: number | null;
          longtaskcount: number | null;
          longtasks: Json | null;
          page_address: string;
          page_filmstrip: string | null;
          page_generator: string | null;
          page_loading_video_max: string | null;
          page_loading_video_mean: string | null;
          page_loading_video_min: string | null;
          page_screenshot: string | null;
          pageweight: number | null;
          performance_score_max: number | null;
          performance_score_mean: number | null;
          performance_score_min: number | null;
          record_id: string;
          resource_count: number | null;
          third_party_content_size_max: number | null;
          third_party_content_size_mean: number | null;
          third_party_content_size_min: number | null;
          third_party_req_max: number | null;
          third_party_req_mean: number | null;
          third_party_req_min: number | null;
          third_party_transfer_size_max: number | null;
          third_party_transfer_size_mean: number | null;
          third_party_transfer_size_min: number | null;
          useragent: string | null;
          windowsize: string | null;
        };
        Insert: {
          browser?: string | null;
          browser_version?: string | null;
          cookies_count?: number | null;
          created_at: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_fcp_avg?: number | null;
          crux_fcp_good?: number | null;
          crux_fcp_p75?: number | null;
          crux_fcp_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          crux_ttfb_avg?: number | null;
          crux_ttfb_good?: number | null;
          crux_ttfb_p75?: number | null;
          crux_ttfb_poor?: number | null;
          device_type: string;
          document_decodedbody_size?: number | null;
          document_encodedbody_size?: number | null;
          document_timing?: Json | null;
          document_transfersize?: number | null;
          documentheight?: number | null;
          documenttitle?: string | null;
          dom_complete_max?: number | null;
          dom_complete_mean?: number | null;
          dom_complete_min?: number | null;
          dom_elements_max?: number | null;
          dom_elements_mean?: number | null;
          dom_elements_min?: number | null;
          dom_interactive_max?: number | null;
          dom_interactive_mean?: number | null;
          dom_interactive_min?: number | null;
          domains?: Json | null;
          inp_eventtime_max?: number | null;
          inp_eventtime_mean?: number | null;
          inp_eventtime_min?: number | null;
          inp_latency_max?: number | null;
          inp_latency_mean?: number | null;
          inp_latency_min?: number | null;
          lab_cls_max?: number | null;
          lab_cls_mean?: number | null;
          lab_cls_min?: number | null;
          lab_contentsize?: number | null;
          lab_css_contentsize_max?: number | null;
          lab_css_contentsize_mean?: number | null;
          lab_css_contentsize_min?: number | null;
          lab_css_request_count_max?: number | null;
          lab_css_request_count_mean?: number | null;
          lab_css_request_count_min?: number | null;
          lab_css_transfersize_max?: number | null;
          lab_css_transfersize_mean?: number | null;
          lab_css_transfersize_min?: number | null;
          lab_domain_lookup?: number | null;
          lab_error_max?: number | null;
          lab_error_mean?: number | null;
          lab_error_min?: number | null;
          lab_fcp_max?: number | null;
          lab_fcp_mean?: number | null;
          lab_fcp_min?: number | null;
          lab_fid_max?: number | null;
          lab_fid_mean?: number | null;
          lab_fid_min?: number | null;
          lab_firstmeaningfulpaint_max?: number | null;
          lab_firstmeaningfulpaint_mean?: number | null;
          lab_firstmeaningfulpaint_min?: number | null;
          lab_font_contentsize_max?: number | null;
          lab_font_contentsize_mean?: number | null;
          lab_font_contentsize_min?: number | null;
          lab_font_request_count_max?: number | null;
          lab_font_request_count_mean?: number | null;
          lab_font_request_count_min?: number | null;
          lab_font_transfersize_max?: number | null;
          lab_font_transfersize_mean?: number | null;
          lab_font_transfersize_min?: number | null;
          lab_fullyloaded_max?: number | null;
          lab_fullyloaded_mean?: number | null;
          lab_fullyloaded_min?: number | null;
          lab_html_contentsize_max?: number | null;
          lab_html_contentsize_mean?: number | null;
          lab_html_contentsize_min?: number | null;
          lab_html_request_count_max?: number | null;
          lab_html_request_count_mean?: number | null;
          lab_html_request_count_min?: number | null;
          lab_html_transfersize_max?: number | null;
          lab_html_transfersize_mean?: number | null;
          lab_html_transfersize_min?: number | null;
          lab_image_contentsize_max?: number | null;
          lab_image_contentsize_mean?: number | null;
          lab_image_contentsize_min?: number | null;
          lab_image_request_count_max?: number | null;
          lab_image_request_count_mean?: number | null;
          lab_image_request_count_min?: number | null;
          lab_image_transfersize_max?: number | null;
          lab_image_transfersize_mean?: number | null;
          lab_image_transfersize_min?: number | null;
          lab_js_contentsize_max?: number | null;
          lab_js_contentsize_mean?: number | null;
          lab_js_contentsize_min?: number | null;
          lab_js_request_count_max?: number | null;
          lab_js_request_count_mean?: number | null;
          lab_js_request_count_min?: number | null;
          lab_js_transfersize_max?: number | null;
          lab_js_transfersize_mean?: number | null;
          lab_js_transfersize_min?: number | null;
          lab_json_contentsize_max?: number | null;
          lab_json_contentsize_mean?: number | null;
          lab_json_contentsize_min?: number | null;
          lab_json_request_count_max?: number | null;
          lab_json_request_count_mean?: number | null;
          lab_json_request_count_min?: number | null;
          lab_json_transfersize_max?: number | null;
          lab_json_transfersize_mean?: number | null;
          lab_json_transfersize_min?: number | null;
          lab_lcp_max?: number | null;
          lab_lcp_mean?: number | null;
          lab_lcp_min?: number | null;
          lab_speed_index_max?: number | null;
          lab_speed_index_mean?: number | null;
          lab_speed_index_min?: number | null;
          lab_srt_max?: number | null;
          lab_srt_mean?: number | null;
          lab_srt_min?: number | null;
          lab_svg_contentsize_max?: number | null;
          lab_svg_contentsize_mean?: number | null;
          lab_svg_contentsize_min?: number | null;
          lab_svg_request_count_max?: number | null;
          lab_svg_request_count_mean?: number | null;
          lab_svg_request_count_min?: number | null;
          lab_svg_transfersize_max?: number | null;
          lab_svg_transfersize_mean?: number | null;
          lab_svg_transfersize_min?: number | null;
          lab_tbt_max?: number | null;
          lab_tbt_mean?: number | null;
          lab_tbt_min?: number | null;
          lab_total_contentsize_max?: number | null;
          lab_total_contentsize_mean?: number | null;
          lab_total_contentsize_min?: number | null;
          lab_total_requests_max?: number | null;
          lab_total_requests_mean?: number | null;
          lab_total_requests_min?: number | null;
          lab_total_transfersize_max?: number | null;
          lab_total_transfersize_mean?: number | null;
          lab_total_transfersize_min?: number | null;
          lab_ttfb_max?: number | null;
          lab_ttfb_mean?: number | null;
          lab_ttfb_min?: number | null;
          last_visual_change_max?: number | null;
          last_visual_change_mean?: number | null;
          last_visual_change_min?: number | null;
          lcp_element_size_max?: number | null;
          lcp_element_size_mean?: number | null;
          lcp_element_size_min?: number | null;
          longtaskcount?: number | null;
          longtasks?: Json | null;
          page_address: string;
          page_filmstrip?: string | null;
          page_generator?: string | null;
          page_loading_video_max?: string | null;
          page_loading_video_mean?: string | null;
          page_loading_video_min?: string | null;
          page_screenshot?: string | null;
          pageweight?: number | null;
          performance_score_max?: number | null;
          performance_score_mean?: number | null;
          performance_score_min?: number | null;
          record_id?: string;
          resource_count?: number | null;
          third_party_content_size_max?: number | null;
          third_party_content_size_mean?: number | null;
          third_party_content_size_min?: number | null;
          third_party_req_max?: number | null;
          third_party_req_mean?: number | null;
          third_party_req_min?: number | null;
          third_party_transfer_size_max?: number | null;
          third_party_transfer_size_mean?: number | null;
          third_party_transfer_size_min?: number | null;
          useragent?: string | null;
          windowsize?: string | null;
        };
        Update: {
          browser?: string | null;
          browser_version?: string | null;
          cookies_count?: number | null;
          created_at?: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_fcp_avg?: number | null;
          crux_fcp_good?: number | null;
          crux_fcp_p75?: number | null;
          crux_fcp_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          crux_ttfb_avg?: number | null;
          crux_ttfb_good?: number | null;
          crux_ttfb_p75?: number | null;
          crux_ttfb_poor?: number | null;
          device_type?: string;
          document_decodedbody_size?: number | null;
          document_encodedbody_size?: number | null;
          document_timing?: Json | null;
          document_transfersize?: number | null;
          documentheight?: number | null;
          documenttitle?: string | null;
          dom_complete_max?: number | null;
          dom_complete_mean?: number | null;
          dom_complete_min?: number | null;
          dom_elements_max?: number | null;
          dom_elements_mean?: number | null;
          dom_elements_min?: number | null;
          dom_interactive_max?: number | null;
          dom_interactive_mean?: number | null;
          dom_interactive_min?: number | null;
          domains?: Json | null;
          inp_eventtime_max?: number | null;
          inp_eventtime_mean?: number | null;
          inp_eventtime_min?: number | null;
          inp_latency_max?: number | null;
          inp_latency_mean?: number | null;
          inp_latency_min?: number | null;
          lab_cls_max?: number | null;
          lab_cls_mean?: number | null;
          lab_cls_min?: number | null;
          lab_contentsize?: number | null;
          lab_css_contentsize_max?: number | null;
          lab_css_contentsize_mean?: number | null;
          lab_css_contentsize_min?: number | null;
          lab_css_request_count_max?: number | null;
          lab_css_request_count_mean?: number | null;
          lab_css_request_count_min?: number | null;
          lab_css_transfersize_max?: number | null;
          lab_css_transfersize_mean?: number | null;
          lab_css_transfersize_min?: number | null;
          lab_domain_lookup?: number | null;
          lab_error_max?: number | null;
          lab_error_mean?: number | null;
          lab_error_min?: number | null;
          lab_fcp_max?: number | null;
          lab_fcp_mean?: number | null;
          lab_fcp_min?: number | null;
          lab_fid_max?: number | null;
          lab_fid_mean?: number | null;
          lab_fid_min?: number | null;
          lab_firstmeaningfulpaint_max?: number | null;
          lab_firstmeaningfulpaint_mean?: number | null;
          lab_firstmeaningfulpaint_min?: number | null;
          lab_font_contentsize_max?: number | null;
          lab_font_contentsize_mean?: number | null;
          lab_font_contentsize_min?: number | null;
          lab_font_request_count_max?: number | null;
          lab_font_request_count_mean?: number | null;
          lab_font_request_count_min?: number | null;
          lab_font_transfersize_max?: number | null;
          lab_font_transfersize_mean?: number | null;
          lab_font_transfersize_min?: number | null;
          lab_fullyloaded_max?: number | null;
          lab_fullyloaded_mean?: number | null;
          lab_fullyloaded_min?: number | null;
          lab_html_contentsize_max?: number | null;
          lab_html_contentsize_mean?: number | null;
          lab_html_contentsize_min?: number | null;
          lab_html_request_count_max?: number | null;
          lab_html_request_count_mean?: number | null;
          lab_html_request_count_min?: number | null;
          lab_html_transfersize_max?: number | null;
          lab_html_transfersize_mean?: number | null;
          lab_html_transfersize_min?: number | null;
          lab_image_contentsize_max?: number | null;
          lab_image_contentsize_mean?: number | null;
          lab_image_contentsize_min?: number | null;
          lab_image_request_count_max?: number | null;
          lab_image_request_count_mean?: number | null;
          lab_image_request_count_min?: number | null;
          lab_image_transfersize_max?: number | null;
          lab_image_transfersize_mean?: number | null;
          lab_image_transfersize_min?: number | null;
          lab_js_contentsize_max?: number | null;
          lab_js_contentsize_mean?: number | null;
          lab_js_contentsize_min?: number | null;
          lab_js_request_count_max?: number | null;
          lab_js_request_count_mean?: number | null;
          lab_js_request_count_min?: number | null;
          lab_js_transfersize_max?: number | null;
          lab_js_transfersize_mean?: number | null;
          lab_js_transfersize_min?: number | null;
          lab_json_contentsize_max?: number | null;
          lab_json_contentsize_mean?: number | null;
          lab_json_contentsize_min?: number | null;
          lab_json_request_count_max?: number | null;
          lab_json_request_count_mean?: number | null;
          lab_json_request_count_min?: number | null;
          lab_json_transfersize_max?: number | null;
          lab_json_transfersize_mean?: number | null;
          lab_json_transfersize_min?: number | null;
          lab_lcp_max?: number | null;
          lab_lcp_mean?: number | null;
          lab_lcp_min?: number | null;
          lab_speed_index_max?: number | null;
          lab_speed_index_mean?: number | null;
          lab_speed_index_min?: number | null;
          lab_srt_max?: number | null;
          lab_srt_mean?: number | null;
          lab_srt_min?: number | null;
          lab_svg_contentsize_max?: number | null;
          lab_svg_contentsize_mean?: number | null;
          lab_svg_contentsize_min?: number | null;
          lab_svg_request_count_max?: number | null;
          lab_svg_request_count_mean?: number | null;
          lab_svg_request_count_min?: number | null;
          lab_svg_transfersize_max?: number | null;
          lab_svg_transfersize_mean?: number | null;
          lab_svg_transfersize_min?: number | null;
          lab_tbt_max?: number | null;
          lab_tbt_mean?: number | null;
          lab_tbt_min?: number | null;
          lab_total_contentsize_max?: number | null;
          lab_total_contentsize_mean?: number | null;
          lab_total_contentsize_min?: number | null;
          lab_total_requests_max?: number | null;
          lab_total_requests_mean?: number | null;
          lab_total_requests_min?: number | null;
          lab_total_transfersize_max?: number | null;
          lab_total_transfersize_mean?: number | null;
          lab_total_transfersize_min?: number | null;
          lab_ttfb_max?: number | null;
          lab_ttfb_mean?: number | null;
          lab_ttfb_min?: number | null;
          last_visual_change_max?: number | null;
          last_visual_change_mean?: number | null;
          last_visual_change_min?: number | null;
          lcp_element_size_max?: number | null;
          lcp_element_size_mean?: number | null;
          lcp_element_size_min?: number | null;
          longtaskcount?: number | null;
          longtasks?: Json | null;
          page_address?: string;
          page_filmstrip?: string | null;
          page_generator?: string | null;
          page_loading_video_max?: string | null;
          page_loading_video_mean?: string | null;
          page_loading_video_min?: string | null;
          page_screenshot?: string | null;
          pageweight?: number | null;
          performance_score_max?: number | null;
          performance_score_mean?: number | null;
          performance_score_min?: number | null;
          record_id?: string;
          resource_count?: number | null;
          third_party_content_size_max?: number | null;
          third_party_content_size_mean?: number | null;
          third_party_content_size_min?: number | null;
          third_party_req_max?: number | null;
          third_party_req_mean?: number | null;
          third_party_req_min?: number | null;
          third_party_transfer_size_max?: number | null;
          third_party_transfer_size_mean?: number | null;
          third_party_transfer_size_min?: number | null;
          useragent?: string | null;
          windowsize?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "fk_page_url";
            columns: ["page_address"];
            isOneToOne: false;
            referencedRelation: "page_monitoring";
            referencedColumns: ["url"];
          },
        ];
      };
      pageperf_data_desktop: {
        Row: {
          browser: string | null;
          browser_version: string | null;
          cookies_count: number | null;
          created_at: string;
          crux_cls_avg: number | null;
          crux_cls_good: number | null;
          crux_cls_p75: number | null;
          crux_cls_poor: number | null;
          crux_fcp_avg: number | null;
          crux_fcp_good: number | null;
          crux_fcp_p75: number | null;
          crux_fcp_poor: number | null;
          crux_inp_avg: number | null;
          crux_inp_good: number | null;
          crux_inp_p75: number | null;
          crux_inp_poor: number | null;
          crux_lcp_avg: number | null;
          crux_lcp_good: number | null;
          crux_lcp_p75: number | null;
          crux_lcp_poor: number | null;
          crux_ttfb_avg: number | null;
          crux_ttfb_good: number | null;
          crux_ttfb_p75: number | null;
          crux_ttfb_poor: number | null;
          device_type: string;
          document_decodedbody_size: number | null;
          document_encodedbody_size: number | null;
          document_timing: Json | null;
          document_transfersize: number | null;
          documentheight: number | null;
          documenttitle: string | null;
          dom_complete_max: number | null;
          dom_complete_mean: number | null;
          dom_complete_min: number | null;
          dom_elements_max: number | null;
          dom_elements_mean: number | null;
          dom_elements_min: number | null;
          dom_interactive_max: number | null;
          dom_interactive_mean: number | null;
          dom_interactive_min: number | null;
          domains: Json | null;
          inp_eventtime_max: number | null;
          inp_eventtime_mean: number | null;
          inp_eventtime_min: number | null;
          inp_latency_max: number | null;
          inp_latency_mean: number | null;
          inp_latency_min: number | null;
          lab_cls_max: number | null;
          lab_cls_mean: number | null;
          lab_cls_min: number | null;
          lab_contentsize: number | null;
          lab_css_contentsize_max: number | null;
          lab_css_contentsize_mean: number | null;
          lab_css_contentsize_min: number | null;
          lab_css_request_count_max: number | null;
          lab_css_request_count_mean: number | null;
          lab_css_request_count_min: number | null;
          lab_css_transfersize_max: number | null;
          lab_css_transfersize_mean: number | null;
          lab_css_transfersize_min: number | null;
          lab_domain_lookup: number | null;
          lab_error_max: number | null;
          lab_error_mean: number | null;
          lab_error_min: number | null;
          lab_fcp_max: number | null;
          lab_fcp_mean: number | null;
          lab_fcp_min: number | null;
          lab_fid_max: number | null;
          lab_fid_mean: number | null;
          lab_fid_min: number | null;
          lab_firstmeaningfulpaint_max: number | null;
          lab_firstmeaningfulpaint_mean: number | null;
          lab_firstmeaningfulpaint_min: number | null;
          lab_font_contentsize_max: number | null;
          lab_font_contentsize_mean: number | null;
          lab_font_contentsize_min: number | null;
          lab_font_request_count_max: number | null;
          lab_font_request_count_mean: number | null;
          lab_font_request_count_min: number | null;
          lab_font_transfersize_max: number | null;
          lab_font_transfersize_mean: number | null;
          lab_font_transfersize_min: number | null;
          lab_fullyloaded_max: number | null;
          lab_fullyloaded_mean: number | null;
          lab_fullyloaded_min: number | null;
          lab_html_contentsize_max: number | null;
          lab_html_contentsize_mean: number | null;
          lab_html_contentsize_min: number | null;
          lab_html_request_count_max: number | null;
          lab_html_request_count_mean: number | null;
          lab_html_request_count_min: number | null;
          lab_html_transfersize_max: number | null;
          lab_html_transfersize_mean: number | null;
          lab_html_transfersize_min: number | null;
          lab_image_contentsize_max: number | null;
          lab_image_contentsize_mean: number | null;
          lab_image_contentsize_min: number | null;
          lab_image_request_count_max: number | null;
          lab_image_request_count_mean: number | null;
          lab_image_request_count_min: number | null;
          lab_image_transfersize_max: number | null;
          lab_image_transfersize_mean: number | null;
          lab_image_transfersize_min: number | null;
          lab_js_contentsize_max: number | null;
          lab_js_contentsize_mean: number | null;
          lab_js_contentsize_min: number | null;
          lab_js_request_count_max: number | null;
          lab_js_request_count_mean: number | null;
          lab_js_request_count_min: number | null;
          lab_js_transfersize_max: number | null;
          lab_js_transfersize_mean: number | null;
          lab_js_transfersize_min: number | null;
          lab_json_contentsize_max: number | null;
          lab_json_contentsize_mean: number | null;
          lab_json_contentsize_min: number | null;
          lab_json_request_count_max: number | null;
          lab_json_request_count_mean: number | null;
          lab_json_request_count_min: number | null;
          lab_json_transfersize_max: number | null;
          lab_json_transfersize_mean: number | null;
          lab_json_transfersize_min: number | null;
          lab_lcp_max: number | null;
          lab_lcp_mean: number | null;
          lab_lcp_min: number | null;
          lab_speed_index_max: number | null;
          lab_speed_index_mean: number | null;
          lab_speed_index_min: number | null;
          lab_srt_max: number | null;
          lab_srt_mean: number | null;
          lab_srt_min: number | null;
          lab_svg_contentsize_max: number | null;
          lab_svg_contentsize_mean: number | null;
          lab_svg_contentsize_min: number | null;
          lab_svg_request_count_max: number | null;
          lab_svg_request_count_mean: number | null;
          lab_svg_request_count_min: number | null;
          lab_svg_transfersize_max: number | null;
          lab_svg_transfersize_mean: number | null;
          lab_svg_transfersize_min: number | null;
          lab_tbt_max: number | null;
          lab_tbt_mean: number | null;
          lab_tbt_min: number | null;
          lab_total_contentsize_max: number | null;
          lab_total_contentsize_mean: number | null;
          lab_total_contentsize_min: number | null;
          lab_total_requests_max: number | null;
          lab_total_requests_mean: number | null;
          lab_total_requests_min: number | null;
          lab_total_transfersize_max: number | null;
          lab_total_transfersize_mean: number | null;
          lab_total_transfersize_min: number | null;
          lab_ttfb_max: number | null;
          lab_ttfb_mean: number | null;
          lab_ttfb_min: number | null;
          last_visual_change_max: number | null;
          last_visual_change_mean: number | null;
          last_visual_change_min: number | null;
          lcp_element_size_max: number | null;
          lcp_element_size_mean: number | null;
          lcp_element_size_min: number | null;
          longtaskcount: number | null;
          longtasks: Json | null;
          page_address: string;
          page_filmstrip: string | null;
          page_generator: string | null;
          page_loading_video_max: string | null;
          page_loading_video_mean: string | null;
          page_loading_video_min: string | null;
          page_screenshot: string | null;
          pageweight: number | null;
          performance_score_max: number | null;
          performance_score_mean: number | null;
          performance_score_min: number | null;
          record_id: string;
          resource_count: number | null;
          third_party_content_size_max: number | null;
          third_party_content_size_mean: number | null;
          third_party_content_size_min: number | null;
          third_party_req_max: number | null;
          third_party_req_mean: number | null;
          third_party_req_min: number | null;
          third_party_transfer_size_max: number | null;
          third_party_transfer_size_mean: number | null;
          third_party_transfer_size_min: number | null;
          useragent: string | null;
          windowsize: string | null;
        };
        Insert: {
          browser?: string | null;
          browser_version?: string | null;
          cookies_count?: number | null;
          created_at: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_fcp_avg?: number | null;
          crux_fcp_good?: number | null;
          crux_fcp_p75?: number | null;
          crux_fcp_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          crux_ttfb_avg?: number | null;
          crux_ttfb_good?: number | null;
          crux_ttfb_p75?: number | null;
          crux_ttfb_poor?: number | null;
          device_type: string;
          document_decodedbody_size?: number | null;
          document_encodedbody_size?: number | null;
          document_timing?: Json | null;
          document_transfersize?: number | null;
          documentheight?: number | null;
          documenttitle?: string | null;
          dom_complete_max?: number | null;
          dom_complete_mean?: number | null;
          dom_complete_min?: number | null;
          dom_elements_max?: number | null;
          dom_elements_mean?: number | null;
          dom_elements_min?: number | null;
          dom_interactive_max?: number | null;
          dom_interactive_mean?: number | null;
          dom_interactive_min?: number | null;
          domains?: Json | null;
          inp_eventtime_max?: number | null;
          inp_eventtime_mean?: number | null;
          inp_eventtime_min?: number | null;
          inp_latency_max?: number | null;
          inp_latency_mean?: number | null;
          inp_latency_min?: number | null;
          lab_cls_max?: number | null;
          lab_cls_mean?: number | null;
          lab_cls_min?: number | null;
          lab_contentsize?: number | null;
          lab_css_contentsize_max?: number | null;
          lab_css_contentsize_mean?: number | null;
          lab_css_contentsize_min?: number | null;
          lab_css_request_count_max?: number | null;
          lab_css_request_count_mean?: number | null;
          lab_css_request_count_min?: number | null;
          lab_css_transfersize_max?: number | null;
          lab_css_transfersize_mean?: number | null;
          lab_css_transfersize_min?: number | null;
          lab_domain_lookup?: number | null;
          lab_error_max?: number | null;
          lab_error_mean?: number | null;
          lab_error_min?: number | null;
          lab_fcp_max?: number | null;
          lab_fcp_mean?: number | null;
          lab_fcp_min?: number | null;
          lab_fid_max?: number | null;
          lab_fid_mean?: number | null;
          lab_fid_min?: number | null;
          lab_firstmeaningfulpaint_max?: number | null;
          lab_firstmeaningfulpaint_mean?: number | null;
          lab_firstmeaningfulpaint_min?: number | null;
          lab_font_contentsize_max?: number | null;
          lab_font_contentsize_mean?: number | null;
          lab_font_contentsize_min?: number | null;
          lab_font_request_count_max?: number | null;
          lab_font_request_count_mean?: number | null;
          lab_font_request_count_min?: number | null;
          lab_font_transfersize_max?: number | null;
          lab_font_transfersize_mean?: number | null;
          lab_font_transfersize_min?: number | null;
          lab_fullyloaded_max?: number | null;
          lab_fullyloaded_mean?: number | null;
          lab_fullyloaded_min?: number | null;
          lab_html_contentsize_max?: number | null;
          lab_html_contentsize_mean?: number | null;
          lab_html_contentsize_min?: number | null;
          lab_html_request_count_max?: number | null;
          lab_html_request_count_mean?: number | null;
          lab_html_request_count_min?: number | null;
          lab_html_transfersize_max?: number | null;
          lab_html_transfersize_mean?: number | null;
          lab_html_transfersize_min?: number | null;
          lab_image_contentsize_max?: number | null;
          lab_image_contentsize_mean?: number | null;
          lab_image_contentsize_min?: number | null;
          lab_image_request_count_max?: number | null;
          lab_image_request_count_mean?: number | null;
          lab_image_request_count_min?: number | null;
          lab_image_transfersize_max?: number | null;
          lab_image_transfersize_mean?: number | null;
          lab_image_transfersize_min?: number | null;
          lab_js_contentsize_max?: number | null;
          lab_js_contentsize_mean?: number | null;
          lab_js_contentsize_min?: number | null;
          lab_js_request_count_max?: number | null;
          lab_js_request_count_mean?: number | null;
          lab_js_request_count_min?: number | null;
          lab_js_transfersize_max?: number | null;
          lab_js_transfersize_mean?: number | null;
          lab_js_transfersize_min?: number | null;
          lab_json_contentsize_max?: number | null;
          lab_json_contentsize_mean?: number | null;
          lab_json_contentsize_min?: number | null;
          lab_json_request_count_max?: number | null;
          lab_json_request_count_mean?: number | null;
          lab_json_request_count_min?: number | null;
          lab_json_transfersize_max?: number | null;
          lab_json_transfersize_mean?: number | null;
          lab_json_transfersize_min?: number | null;
          lab_lcp_max?: number | null;
          lab_lcp_mean?: number | null;
          lab_lcp_min?: number | null;
          lab_speed_index_max?: number | null;
          lab_speed_index_mean?: number | null;
          lab_speed_index_min?: number | null;
          lab_srt_max?: number | null;
          lab_srt_mean?: number | null;
          lab_srt_min?: number | null;
          lab_svg_contentsize_max?: number | null;
          lab_svg_contentsize_mean?: number | null;
          lab_svg_contentsize_min?: number | null;
          lab_svg_request_count_max?: number | null;
          lab_svg_request_count_mean?: number | null;
          lab_svg_request_count_min?: number | null;
          lab_svg_transfersize_max?: number | null;
          lab_svg_transfersize_mean?: number | null;
          lab_svg_transfersize_min?: number | null;
          lab_tbt_max?: number | null;
          lab_tbt_mean?: number | null;
          lab_tbt_min?: number | null;
          lab_total_contentsize_max?: number | null;
          lab_total_contentsize_mean?: number | null;
          lab_total_contentsize_min?: number | null;
          lab_total_requests_max?: number | null;
          lab_total_requests_mean?: number | null;
          lab_total_requests_min?: number | null;
          lab_total_transfersize_max?: number | null;
          lab_total_transfersize_mean?: number | null;
          lab_total_transfersize_min?: number | null;
          lab_ttfb_max?: number | null;
          lab_ttfb_mean?: number | null;
          lab_ttfb_min?: number | null;
          last_visual_change_max?: number | null;
          last_visual_change_mean?: number | null;
          last_visual_change_min?: number | null;
          lcp_element_size_max?: number | null;
          lcp_element_size_mean?: number | null;
          lcp_element_size_min?: number | null;
          longtaskcount?: number | null;
          longtasks?: Json | null;
          page_address: string;
          page_filmstrip?: string | null;
          page_generator?: string | null;
          page_loading_video_max?: string | null;
          page_loading_video_mean?: string | null;
          page_loading_video_min?: string | null;
          page_screenshot?: string | null;
          pageweight?: number | null;
          performance_score_max?: number | null;
          performance_score_mean?: number | null;
          performance_score_min?: number | null;
          record_id?: string;
          resource_count?: number | null;
          third_party_content_size_max?: number | null;
          third_party_content_size_mean?: number | null;
          third_party_content_size_min?: number | null;
          third_party_req_max?: number | null;
          third_party_req_mean?: number | null;
          third_party_req_min?: number | null;
          third_party_transfer_size_max?: number | null;
          third_party_transfer_size_mean?: number | null;
          third_party_transfer_size_min?: number | null;
          useragent?: string | null;
          windowsize?: string | null;
        };
        Update: {
          browser?: string | null;
          browser_version?: string | null;
          cookies_count?: number | null;
          created_at?: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_fcp_avg?: number | null;
          crux_fcp_good?: number | null;
          crux_fcp_p75?: number | null;
          crux_fcp_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          crux_ttfb_avg?: number | null;
          crux_ttfb_good?: number | null;
          crux_ttfb_p75?: number | null;
          crux_ttfb_poor?: number | null;
          device_type?: string;
          document_decodedbody_size?: number | null;
          document_encodedbody_size?: number | null;
          document_timing?: Json | null;
          document_transfersize?: number | null;
          documentheight?: number | null;
          documenttitle?: string | null;
          dom_complete_max?: number | null;
          dom_complete_mean?: number | null;
          dom_complete_min?: number | null;
          dom_elements_max?: number | null;
          dom_elements_mean?: number | null;
          dom_elements_min?: number | null;
          dom_interactive_max?: number | null;
          dom_interactive_mean?: number | null;
          dom_interactive_min?: number | null;
          domains?: Json | null;
          inp_eventtime_max?: number | null;
          inp_eventtime_mean?: number | null;
          inp_eventtime_min?: number | null;
          inp_latency_max?: number | null;
          inp_latency_mean?: number | null;
          inp_latency_min?: number | null;
          lab_cls_max?: number | null;
          lab_cls_mean?: number | null;
          lab_cls_min?: number | null;
          lab_contentsize?: number | null;
          lab_css_contentsize_max?: number | null;
          lab_css_contentsize_mean?: number | null;
          lab_css_contentsize_min?: number | null;
          lab_css_request_count_max?: number | null;
          lab_css_request_count_mean?: number | null;
          lab_css_request_count_min?: number | null;
          lab_css_transfersize_max?: number | null;
          lab_css_transfersize_mean?: number | null;
          lab_css_transfersize_min?: number | null;
          lab_domain_lookup?: number | null;
          lab_error_max?: number | null;
          lab_error_mean?: number | null;
          lab_error_min?: number | null;
          lab_fcp_max?: number | null;
          lab_fcp_mean?: number | null;
          lab_fcp_min?: number | null;
          lab_fid_max?: number | null;
          lab_fid_mean?: number | null;
          lab_fid_min?: number | null;
          lab_firstmeaningfulpaint_max?: number | null;
          lab_firstmeaningfulpaint_mean?: number | null;
          lab_firstmeaningfulpaint_min?: number | null;
          lab_font_contentsize_max?: number | null;
          lab_font_contentsize_mean?: number | null;
          lab_font_contentsize_min?: number | null;
          lab_font_request_count_max?: number | null;
          lab_font_request_count_mean?: number | null;
          lab_font_request_count_min?: number | null;
          lab_font_transfersize_max?: number | null;
          lab_font_transfersize_mean?: number | null;
          lab_font_transfersize_min?: number | null;
          lab_fullyloaded_max?: number | null;
          lab_fullyloaded_mean?: number | null;
          lab_fullyloaded_min?: number | null;
          lab_html_contentsize_max?: number | null;
          lab_html_contentsize_mean?: number | null;
          lab_html_contentsize_min?: number | null;
          lab_html_request_count_max?: number | null;
          lab_html_request_count_mean?: number | null;
          lab_html_request_count_min?: number | null;
          lab_html_transfersize_max?: number | null;
          lab_html_transfersize_mean?: number | null;
          lab_html_transfersize_min?: number | null;
          lab_image_contentsize_max?: number | null;
          lab_image_contentsize_mean?: number | null;
          lab_image_contentsize_min?: number | null;
          lab_image_request_count_max?: number | null;
          lab_image_request_count_mean?: number | null;
          lab_image_request_count_min?: number | null;
          lab_image_transfersize_max?: number | null;
          lab_image_transfersize_mean?: number | null;
          lab_image_transfersize_min?: number | null;
          lab_js_contentsize_max?: number | null;
          lab_js_contentsize_mean?: number | null;
          lab_js_contentsize_min?: number | null;
          lab_js_request_count_max?: number | null;
          lab_js_request_count_mean?: number | null;
          lab_js_request_count_min?: number | null;
          lab_js_transfersize_max?: number | null;
          lab_js_transfersize_mean?: number | null;
          lab_js_transfersize_min?: number | null;
          lab_json_contentsize_max?: number | null;
          lab_json_contentsize_mean?: number | null;
          lab_json_contentsize_min?: number | null;
          lab_json_request_count_max?: number | null;
          lab_json_request_count_mean?: number | null;
          lab_json_request_count_min?: number | null;
          lab_json_transfersize_max?: number | null;
          lab_json_transfersize_mean?: number | null;
          lab_json_transfersize_min?: number | null;
          lab_lcp_max?: number | null;
          lab_lcp_mean?: number | null;
          lab_lcp_min?: number | null;
          lab_speed_index_max?: number | null;
          lab_speed_index_mean?: number | null;
          lab_speed_index_min?: number | null;
          lab_srt_max?: number | null;
          lab_srt_mean?: number | null;
          lab_srt_min?: number | null;
          lab_svg_contentsize_max?: number | null;
          lab_svg_contentsize_mean?: number | null;
          lab_svg_contentsize_min?: number | null;
          lab_svg_request_count_max?: number | null;
          lab_svg_request_count_mean?: number | null;
          lab_svg_request_count_min?: number | null;
          lab_svg_transfersize_max?: number | null;
          lab_svg_transfersize_mean?: number | null;
          lab_svg_transfersize_min?: number | null;
          lab_tbt_max?: number | null;
          lab_tbt_mean?: number | null;
          lab_tbt_min?: number | null;
          lab_total_contentsize_max?: number | null;
          lab_total_contentsize_mean?: number | null;
          lab_total_contentsize_min?: number | null;
          lab_total_requests_max?: number | null;
          lab_total_requests_mean?: number | null;
          lab_total_requests_min?: number | null;
          lab_total_transfersize_max?: number | null;
          lab_total_transfersize_mean?: number | null;
          lab_total_transfersize_min?: number | null;
          lab_ttfb_max?: number | null;
          lab_ttfb_mean?: number | null;
          lab_ttfb_min?: number | null;
          last_visual_change_max?: number | null;
          last_visual_change_mean?: number | null;
          last_visual_change_min?: number | null;
          lcp_element_size_max?: number | null;
          lcp_element_size_mean?: number | null;
          lcp_element_size_min?: number | null;
          longtaskcount?: number | null;
          longtasks?: Json | null;
          page_address?: string;
          page_filmstrip?: string | null;
          page_generator?: string | null;
          page_loading_video_max?: string | null;
          page_loading_video_mean?: string | null;
          page_loading_video_min?: string | null;
          page_screenshot?: string | null;
          pageweight?: number | null;
          performance_score_max?: number | null;
          performance_score_mean?: number | null;
          performance_score_min?: number | null;
          record_id?: string;
          resource_count?: number | null;
          third_party_content_size_max?: number | null;
          third_party_content_size_mean?: number | null;
          third_party_content_size_min?: number | null;
          third_party_req_max?: number | null;
          third_party_req_mean?: number | null;
          third_party_req_min?: number | null;
          third_party_transfer_size_max?: number | null;
          third_party_transfer_size_mean?: number | null;
          third_party_transfer_size_min?: number | null;
          useragent?: string | null;
          windowsize?: string | null;
        };
        Relationships: [];
      };
      pageperf_data_mobile: {
        Row: {
          browser: string | null;
          browser_version: string | null;
          cookies_count: number | null;
          created_at: string;
          crux_cls_avg: number | null;
          crux_cls_good: number | null;
          crux_cls_p75: number | null;
          crux_cls_poor: number | null;
          crux_fcp_avg: number | null;
          crux_fcp_good: number | null;
          crux_fcp_p75: number | null;
          crux_fcp_poor: number | null;
          crux_inp_avg: number | null;
          crux_inp_good: number | null;
          crux_inp_p75: number | null;
          crux_inp_poor: number | null;
          crux_lcp_avg: number | null;
          crux_lcp_good: number | null;
          crux_lcp_p75: number | null;
          crux_lcp_poor: number | null;
          crux_ttfb_avg: number | null;
          crux_ttfb_good: number | null;
          crux_ttfb_p75: number | null;
          crux_ttfb_poor: number | null;
          device_type: string;
          document_decodedbody_size: number | null;
          document_encodedbody_size: number | null;
          document_timing: Json | null;
          document_transfersize: number | null;
          documentheight: number | null;
          documenttitle: string | null;
          dom_complete_max: number | null;
          dom_complete_mean: number | null;
          dom_complete_min: number | null;
          dom_elements_max: number | null;
          dom_elements_mean: number | null;
          dom_elements_min: number | null;
          dom_interactive_max: number | null;
          dom_interactive_mean: number | null;
          dom_interactive_min: number | null;
          domains: Json | null;
          inp_eventtime_max: number | null;
          inp_eventtime_mean: number | null;
          inp_eventtime_min: number | null;
          inp_latency_max: number | null;
          inp_latency_mean: number | null;
          inp_latency_min: number | null;
          lab_cls_max: number | null;
          lab_cls_mean: number | null;
          lab_cls_min: number | null;
          lab_contentsize: number | null;
          lab_css_contentsize_max: number | null;
          lab_css_contentsize_mean: number | null;
          lab_css_contentsize_min: number | null;
          lab_css_request_count_max: number | null;
          lab_css_request_count_mean: number | null;
          lab_css_request_count_min: number | null;
          lab_css_transfersize_max: number | null;
          lab_css_transfersize_mean: number | null;
          lab_css_transfersize_min: number | null;
          lab_domain_lookup: number | null;
          lab_error_max: number | null;
          lab_error_mean: number | null;
          lab_error_min: number | null;
          lab_fcp_max: number | null;
          lab_fcp_mean: number | null;
          lab_fcp_min: number | null;
          lab_fid_max: number | null;
          lab_fid_mean: number | null;
          lab_fid_min: number | null;
          lab_firstmeaningfulpaint_max: number | null;
          lab_firstmeaningfulpaint_mean: number | null;
          lab_firstmeaningfulpaint_min: number | null;
          lab_font_contentsize_max: number | null;
          lab_font_contentsize_mean: number | null;
          lab_font_contentsize_min: number | null;
          lab_font_request_count_max: number | null;
          lab_font_request_count_mean: number | null;
          lab_font_request_count_min: number | null;
          lab_font_transfersize_max: number | null;
          lab_font_transfersize_mean: number | null;
          lab_font_transfersize_min: number | null;
          lab_fullyloaded_max: number | null;
          lab_fullyloaded_mean: number | null;
          lab_fullyloaded_min: number | null;
          lab_html_contentsize_max: number | null;
          lab_html_contentsize_mean: number | null;
          lab_html_contentsize_min: number | null;
          lab_html_request_count_max: number | null;
          lab_html_request_count_mean: number | null;
          lab_html_request_count_min: number | null;
          lab_html_transfersize_max: number | null;
          lab_html_transfersize_mean: number | null;
          lab_html_transfersize_min: number | null;
          lab_image_contentsize_max: number | null;
          lab_image_contentsize_mean: number | null;
          lab_image_contentsize_min: number | null;
          lab_image_request_count_max: number | null;
          lab_image_request_count_mean: number | null;
          lab_image_request_count_min: number | null;
          lab_image_transfersize_max: number | null;
          lab_image_transfersize_mean: number | null;
          lab_image_transfersize_min: number | null;
          lab_js_contentsize_max: number | null;
          lab_js_contentsize_mean: number | null;
          lab_js_contentsize_min: number | null;
          lab_js_request_count_max: number | null;
          lab_js_request_count_mean: number | null;
          lab_js_request_count_min: number | null;
          lab_js_transfersize_max: number | null;
          lab_js_transfersize_mean: number | null;
          lab_js_transfersize_min: number | null;
          lab_json_contentsize_max: number | null;
          lab_json_contentsize_mean: number | null;
          lab_json_contentsize_min: number | null;
          lab_json_request_count_max: number | null;
          lab_json_request_count_mean: number | null;
          lab_json_request_count_min: number | null;
          lab_json_transfersize_max: number | null;
          lab_json_transfersize_mean: number | null;
          lab_json_transfersize_min: number | null;
          lab_lcp_max: number | null;
          lab_lcp_mean: number | null;
          lab_lcp_min: number | null;
          lab_speed_index_max: number | null;
          lab_speed_index_mean: number | null;
          lab_speed_index_min: number | null;
          lab_srt_max: number | null;
          lab_srt_mean: number | null;
          lab_srt_min: number | null;
          lab_svg_contentsize_max: number | null;
          lab_svg_contentsize_mean: number | null;
          lab_svg_contentsize_min: number | null;
          lab_svg_request_count_max: number | null;
          lab_svg_request_count_mean: number | null;
          lab_svg_request_count_min: number | null;
          lab_svg_transfersize_max: number | null;
          lab_svg_transfersize_mean: number | null;
          lab_svg_transfersize_min: number | null;
          lab_tbt_max: number | null;
          lab_tbt_mean: number | null;
          lab_tbt_min: number | null;
          lab_total_contentsize_max: number | null;
          lab_total_contentsize_mean: number | null;
          lab_total_contentsize_min: number | null;
          lab_total_requests_max: number | null;
          lab_total_requests_mean: number | null;
          lab_total_requests_min: number | null;
          lab_total_transfersize_max: number | null;
          lab_total_transfersize_mean: number | null;
          lab_total_transfersize_min: number | null;
          lab_ttfb_max: number | null;
          lab_ttfb_mean: number | null;
          lab_ttfb_min: number | null;
          last_visual_change_max: number | null;
          last_visual_change_mean: number | null;
          last_visual_change_min: number | null;
          lcp_element_size_max: number | null;
          lcp_element_size_mean: number | null;
          lcp_element_size_min: number | null;
          longtaskcount: number | null;
          longtasks: Json | null;
          page_address: string;
          page_filmstrip: string | null;
          page_generator: string | null;
          page_loading_video_max: string | null;
          page_loading_video_mean: string | null;
          page_loading_video_min: string | null;
          page_screenshot: string | null;
          pageweight: number | null;
          performance_score_max: number | null;
          performance_score_mean: number | null;
          performance_score_min: number | null;
          record_id: string;
          resource_count: number | null;
          third_party_content_size_max: number | null;
          third_party_content_size_mean: number | null;
          third_party_content_size_min: number | null;
          third_party_req_max: number | null;
          third_party_req_mean: number | null;
          third_party_req_min: number | null;
          third_party_transfer_size_max: number | null;
          third_party_transfer_size_mean: number | null;
          third_party_transfer_size_min: number | null;
          useragent: string | null;
          windowsize: string | null;
        };
        Insert: {
          browser?: string | null;
          browser_version?: string | null;
          cookies_count?: number | null;
          created_at: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_fcp_avg?: number | null;
          crux_fcp_good?: number | null;
          crux_fcp_p75?: number | null;
          crux_fcp_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          crux_ttfb_avg?: number | null;
          crux_ttfb_good?: number | null;
          crux_ttfb_p75?: number | null;
          crux_ttfb_poor?: number | null;
          device_type: string;
          document_decodedbody_size?: number | null;
          document_encodedbody_size?: number | null;
          document_timing?: Json | null;
          document_transfersize?: number | null;
          documentheight?: number | null;
          documenttitle?: string | null;
          dom_complete_max?: number | null;
          dom_complete_mean?: number | null;
          dom_complete_min?: number | null;
          dom_elements_max?: number | null;
          dom_elements_mean?: number | null;
          dom_elements_min?: number | null;
          dom_interactive_max?: number | null;
          dom_interactive_mean?: number | null;
          dom_interactive_min?: number | null;
          domains?: Json | null;
          inp_eventtime_max?: number | null;
          inp_eventtime_mean?: number | null;
          inp_eventtime_min?: number | null;
          inp_latency_max?: number | null;
          inp_latency_mean?: number | null;
          inp_latency_min?: number | null;
          lab_cls_max?: number | null;
          lab_cls_mean?: number | null;
          lab_cls_min?: number | null;
          lab_contentsize?: number | null;
          lab_css_contentsize_max?: number | null;
          lab_css_contentsize_mean?: number | null;
          lab_css_contentsize_min?: number | null;
          lab_css_request_count_max?: number | null;
          lab_css_request_count_mean?: number | null;
          lab_css_request_count_min?: number | null;
          lab_css_transfersize_max?: number | null;
          lab_css_transfersize_mean?: number | null;
          lab_css_transfersize_min?: number | null;
          lab_domain_lookup?: number | null;
          lab_error_max?: number | null;
          lab_error_mean?: number | null;
          lab_error_min?: number | null;
          lab_fcp_max?: number | null;
          lab_fcp_mean?: number | null;
          lab_fcp_min?: number | null;
          lab_fid_max?: number | null;
          lab_fid_mean?: number | null;
          lab_fid_min?: number | null;
          lab_firstmeaningfulpaint_max?: number | null;
          lab_firstmeaningfulpaint_mean?: number | null;
          lab_firstmeaningfulpaint_min?: number | null;
          lab_font_contentsize_max?: number | null;
          lab_font_contentsize_mean?: number | null;
          lab_font_contentsize_min?: number | null;
          lab_font_request_count_max?: number | null;
          lab_font_request_count_mean?: number | null;
          lab_font_request_count_min?: number | null;
          lab_font_transfersize_max?: number | null;
          lab_font_transfersize_mean?: number | null;
          lab_font_transfersize_min?: number | null;
          lab_fullyloaded_max?: number | null;
          lab_fullyloaded_mean?: number | null;
          lab_fullyloaded_min?: number | null;
          lab_html_contentsize_max?: number | null;
          lab_html_contentsize_mean?: number | null;
          lab_html_contentsize_min?: number | null;
          lab_html_request_count_max?: number | null;
          lab_html_request_count_mean?: number | null;
          lab_html_request_count_min?: number | null;
          lab_html_transfersize_max?: number | null;
          lab_html_transfersize_mean?: number | null;
          lab_html_transfersize_min?: number | null;
          lab_image_contentsize_max?: number | null;
          lab_image_contentsize_mean?: number | null;
          lab_image_contentsize_min?: number | null;
          lab_image_request_count_max?: number | null;
          lab_image_request_count_mean?: number | null;
          lab_image_request_count_min?: number | null;
          lab_image_transfersize_max?: number | null;
          lab_image_transfersize_mean?: number | null;
          lab_image_transfersize_min?: number | null;
          lab_js_contentsize_max?: number | null;
          lab_js_contentsize_mean?: number | null;
          lab_js_contentsize_min?: number | null;
          lab_js_request_count_max?: number | null;
          lab_js_request_count_mean?: number | null;
          lab_js_request_count_min?: number | null;
          lab_js_transfersize_max?: number | null;
          lab_js_transfersize_mean?: number | null;
          lab_js_transfersize_min?: number | null;
          lab_json_contentsize_max?: number | null;
          lab_json_contentsize_mean?: number | null;
          lab_json_contentsize_min?: number | null;
          lab_json_request_count_max?: number | null;
          lab_json_request_count_mean?: number | null;
          lab_json_request_count_min?: number | null;
          lab_json_transfersize_max?: number | null;
          lab_json_transfersize_mean?: number | null;
          lab_json_transfersize_min?: number | null;
          lab_lcp_max?: number | null;
          lab_lcp_mean?: number | null;
          lab_lcp_min?: number | null;
          lab_speed_index_max?: number | null;
          lab_speed_index_mean?: number | null;
          lab_speed_index_min?: number | null;
          lab_srt_max?: number | null;
          lab_srt_mean?: number | null;
          lab_srt_min?: number | null;
          lab_svg_contentsize_max?: number | null;
          lab_svg_contentsize_mean?: number | null;
          lab_svg_contentsize_min?: number | null;
          lab_svg_request_count_max?: number | null;
          lab_svg_request_count_mean?: number | null;
          lab_svg_request_count_min?: number | null;
          lab_svg_transfersize_max?: number | null;
          lab_svg_transfersize_mean?: number | null;
          lab_svg_transfersize_min?: number | null;
          lab_tbt_max?: number | null;
          lab_tbt_mean?: number | null;
          lab_tbt_min?: number | null;
          lab_total_contentsize_max?: number | null;
          lab_total_contentsize_mean?: number | null;
          lab_total_contentsize_min?: number | null;
          lab_total_requests_max?: number | null;
          lab_total_requests_mean?: number | null;
          lab_total_requests_min?: number | null;
          lab_total_transfersize_max?: number | null;
          lab_total_transfersize_mean?: number | null;
          lab_total_transfersize_min?: number | null;
          lab_ttfb_max?: number | null;
          lab_ttfb_mean?: number | null;
          lab_ttfb_min?: number | null;
          last_visual_change_max?: number | null;
          last_visual_change_mean?: number | null;
          last_visual_change_min?: number | null;
          lcp_element_size_max?: number | null;
          lcp_element_size_mean?: number | null;
          lcp_element_size_min?: number | null;
          longtaskcount?: number | null;
          longtasks?: Json | null;
          page_address: string;
          page_filmstrip?: string | null;
          page_generator?: string | null;
          page_loading_video_max?: string | null;
          page_loading_video_mean?: string | null;
          page_loading_video_min?: string | null;
          page_screenshot?: string | null;
          pageweight?: number | null;
          performance_score_max?: number | null;
          performance_score_mean?: number | null;
          performance_score_min?: number | null;
          record_id?: string;
          resource_count?: number | null;
          third_party_content_size_max?: number | null;
          third_party_content_size_mean?: number | null;
          third_party_content_size_min?: number | null;
          third_party_req_max?: number | null;
          third_party_req_mean?: number | null;
          third_party_req_min?: number | null;
          third_party_transfer_size_max?: number | null;
          third_party_transfer_size_mean?: number | null;
          third_party_transfer_size_min?: number | null;
          useragent?: string | null;
          windowsize?: string | null;
        };
        Update: {
          browser?: string | null;
          browser_version?: string | null;
          cookies_count?: number | null;
          created_at?: string;
          crux_cls_avg?: number | null;
          crux_cls_good?: number | null;
          crux_cls_p75?: number | null;
          crux_cls_poor?: number | null;
          crux_fcp_avg?: number | null;
          crux_fcp_good?: number | null;
          crux_fcp_p75?: number | null;
          crux_fcp_poor?: number | null;
          crux_inp_avg?: number | null;
          crux_inp_good?: number | null;
          crux_inp_p75?: number | null;
          crux_inp_poor?: number | null;
          crux_lcp_avg?: number | null;
          crux_lcp_good?: number | null;
          crux_lcp_p75?: number | null;
          crux_lcp_poor?: number | null;
          crux_ttfb_avg?: number | null;
          crux_ttfb_good?: number | null;
          crux_ttfb_p75?: number | null;
          crux_ttfb_poor?: number | null;
          device_type?: string;
          document_decodedbody_size?: number | null;
          document_encodedbody_size?: number | null;
          document_timing?: Json | null;
          document_transfersize?: number | null;
          documentheight?: number | null;
          documenttitle?: string | null;
          dom_complete_max?: number | null;
          dom_complete_mean?: number | null;
          dom_complete_min?: number | null;
          dom_elements_max?: number | null;
          dom_elements_mean?: number | null;
          dom_elements_min?: number | null;
          dom_interactive_max?: number | null;
          dom_interactive_mean?: number | null;
          dom_interactive_min?: number | null;
          domains?: Json | null;
          inp_eventtime_max?: number | null;
          inp_eventtime_mean?: number | null;
          inp_eventtime_min?: number | null;
          inp_latency_max?: number | null;
          inp_latency_mean?: number | null;
          inp_latency_min?: number | null;
          lab_cls_max?: number | null;
          lab_cls_mean?: number | null;
          lab_cls_min?: number | null;
          lab_contentsize?: number | null;
          lab_css_contentsize_max?: number | null;
          lab_css_contentsize_mean?: number | null;
          lab_css_contentsize_min?: number | null;
          lab_css_request_count_max?: number | null;
          lab_css_request_count_mean?: number | null;
          lab_css_request_count_min?: number | null;
          lab_css_transfersize_max?: number | null;
          lab_css_transfersize_mean?: number | null;
          lab_css_transfersize_min?: number | null;
          lab_domain_lookup?: number | null;
          lab_error_max?: number | null;
          lab_error_mean?: number | null;
          lab_error_min?: number | null;
          lab_fcp_max?: number | null;
          lab_fcp_mean?: number | null;
          lab_fcp_min?: number | null;
          lab_fid_max?: number | null;
          lab_fid_mean?: number | null;
          lab_fid_min?: number | null;
          lab_firstmeaningfulpaint_max?: number | null;
          lab_firstmeaningfulpaint_mean?: number | null;
          lab_firstmeaningfulpaint_min?: number | null;
          lab_font_contentsize_max?: number | null;
          lab_font_contentsize_mean?: number | null;
          lab_font_contentsize_min?: number | null;
          lab_font_request_count_max?: number | null;
          lab_font_request_count_mean?: number | null;
          lab_font_request_count_min?: number | null;
          lab_font_transfersize_max?: number | null;
          lab_font_transfersize_mean?: number | null;
          lab_font_transfersize_min?: number | null;
          lab_fullyloaded_max?: number | null;
          lab_fullyloaded_mean?: number | null;
          lab_fullyloaded_min?: number | null;
          lab_html_contentsize_max?: number | null;
          lab_html_contentsize_mean?: number | null;
          lab_html_contentsize_min?: number | null;
          lab_html_request_count_max?: number | null;
          lab_html_request_count_mean?: number | null;
          lab_html_request_count_min?: number | null;
          lab_html_transfersize_max?: number | null;
          lab_html_transfersize_mean?: number | null;
          lab_html_transfersize_min?: number | null;
          lab_image_contentsize_max?: number | null;
          lab_image_contentsize_mean?: number | null;
          lab_image_contentsize_min?: number | null;
          lab_image_request_count_max?: number | null;
          lab_image_request_count_mean?: number | null;
          lab_image_request_count_min?: number | null;
          lab_image_transfersize_max?: number | null;
          lab_image_transfersize_mean?: number | null;
          lab_image_transfersize_min?: number | null;
          lab_js_contentsize_max?: number | null;
          lab_js_contentsize_mean?: number | null;
          lab_js_contentsize_min?: number | null;
          lab_js_request_count_max?: number | null;
          lab_js_request_count_mean?: number | null;
          lab_js_request_count_min?: number | null;
          lab_js_transfersize_max?: number | null;
          lab_js_transfersize_mean?: number | null;
          lab_js_transfersize_min?: number | null;
          lab_json_contentsize_max?: number | null;
          lab_json_contentsize_mean?: number | null;
          lab_json_contentsize_min?: number | null;
          lab_json_request_count_max?: number | null;
          lab_json_request_count_mean?: number | null;
          lab_json_request_count_min?: number | null;
          lab_json_transfersize_max?: number | null;
          lab_json_transfersize_mean?: number | null;
          lab_json_transfersize_min?: number | null;
          lab_lcp_max?: number | null;
          lab_lcp_mean?: number | null;
          lab_lcp_min?: number | null;
          lab_speed_index_max?: number | null;
          lab_speed_index_mean?: number | null;
          lab_speed_index_min?: number | null;
          lab_srt_max?: number | null;
          lab_srt_mean?: number | null;
          lab_srt_min?: number | null;
          lab_svg_contentsize_max?: number | null;
          lab_svg_contentsize_mean?: number | null;
          lab_svg_contentsize_min?: number | null;
          lab_svg_request_count_max?: number | null;
          lab_svg_request_count_mean?: number | null;
          lab_svg_request_count_min?: number | null;
          lab_svg_transfersize_max?: number | null;
          lab_svg_transfersize_mean?: number | null;
          lab_svg_transfersize_min?: number | null;
          lab_tbt_max?: number | null;
          lab_tbt_mean?: number | null;
          lab_tbt_min?: number | null;
          lab_total_contentsize_max?: number | null;
          lab_total_contentsize_mean?: number | null;
          lab_total_contentsize_min?: number | null;
          lab_total_requests_max?: number | null;
          lab_total_requests_mean?: number | null;
          lab_total_requests_min?: number | null;
          lab_total_transfersize_max?: number | null;
          lab_total_transfersize_mean?: number | null;
          lab_total_transfersize_min?: number | null;
          lab_ttfb_max?: number | null;
          lab_ttfb_mean?: number | null;
          lab_ttfb_min?: number | null;
          last_visual_change_max?: number | null;
          last_visual_change_mean?: number | null;
          last_visual_change_min?: number | null;
          lcp_element_size_max?: number | null;
          lcp_element_size_mean?: number | null;
          lcp_element_size_min?: number | null;
          longtaskcount?: number | null;
          longtasks?: Json | null;
          page_address?: string;
          page_filmstrip?: string | null;
          page_generator?: string | null;
          page_loading_video_max?: string | null;
          page_loading_video_mean?: string | null;
          page_loading_video_min?: string | null;
          page_screenshot?: string | null;
          pageweight?: number | null;
          performance_score_max?: number | null;
          performance_score_mean?: number | null;
          performance_score_min?: number | null;
          record_id?: string;
          resource_count?: number | null;
          third_party_content_size_max?: number | null;
          third_party_content_size_mean?: number | null;
          third_party_content_size_min?: number | null;
          third_party_req_max?: number | null;
          third_party_req_mean?: number | null;
          third_party_req_min?: number | null;
          third_party_transfer_size_max?: number | null;
          third_party_transfer_size_mean?: number | null;
          third_party_transfer_size_min?: number | null;
          useragent?: string | null;
          windowsize?: string | null;
        };
        Relationships: [];
      };
      users: {
        Row: {
          created_at: string;
          email: string;
          firstname: string;
          id: string | null;
          lastname: string;
        };
        Insert: {
          created_at?: string;
          email: string;
          firstname: string;
          id?: string | null;
          lastname: string;
        };
        Update: {
          created_at?: string;
          email?: string;
          firstname?: string;
          id?: string | null;
          lastname?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DefaultSchema = Database[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database;
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database;
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database;
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database;
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database;
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
