// export type metric_data = {
//   website_name?: string;
//   device_type?: string;
//   crux_lcp_p75?: number | null;
//   crux_cls_p75?: number | null;
//   crux_inp_p75?: number | null;
//   crux_cls_avg?: number | null;
//   crux_cls_good?: number | null;
//   crux_cls_poor?: number | null;
//   crux_inp_avg?: number | null;
//   crux_inp_good?: number | null;
//   crux_inp_poor?: number | null;
//   crux_lcp_avg?: number | null;
//   crux_lcp_good?: number | null;
//   crux_lcp_poor?: number | null;
//   largest_contentful_paint?: number | null;
//   cumulative_layout_shift?: number | null;
//   first_contentful_paint?: number | null;
//   total_blocking_time?: number | null;
//   server_response_time?: number | null;
//   performance_score?: number | null;
//   bootup_time?: number | null;
//   status?: "passing" | "failing";
//   lh_version?: string | null;
//   network_config?: string | null;
//   total_byte?: number | null;
//   created_at?: string;
//   speed_index?: number | null;
// };
