export {default as ComparisonTable} from "./compairsion-table"
export {default as Home} from "./homepage"
export {default as FeatureBlock} from "./helper"
export {default as SiteHeader} from "./header"
export {default as Testimonials} from "./testimonials"