import { Json } from "@/lib/db/database.types";

export type performance_data = {
  [key: string]: any; // for dynamic access to properties
  browser?: string | null;
  browser_version?: string | null;
  created_at: string;
  crux_cls_avg?: number | null;
  crux_cls_good?: number | null;
  crux_cls_p75?: number | null;
  crux_cls_poor?: number | null;
  crux_inp_avg?: number | null;
  crux_inp_good?: number | null;
  crux_inp_p75?: number | null;
  crux_inp_poor?: number | null;
  crux_lcp_avg?: number | null;
  crux_lcp_good?: number | null;
  crux_lcp_p75?: number | null;
  crux_lcp_poor?: number | null;
  crux_fcp_avg?: number | null;
  crux_fcp_good?: number | null;
  crux_fcp_p75?: number | null;
  crux_fcp_poor?: number | null;
  crux_ttfb_avg?: number | null;
  crux_ttfb_good?: number | null;
  crux_ttfb_p75?: number | null;
  crux_ttfb_poor?: number | null;
  device_type: string;
  document_decodedbody_size?: number | null;
  document_encodedbody_size?: number | null;
  document_timing?: Json | null;
  document_transfersize?: number | null;
  documenttitle?: string | null;
  dom_complete_max?: number | null;
  dom_complete_mean?: number | null;
  dom_complete_min?: number | null;
  dom_elements_max?: number | null;
  dom_elements_mean?: number | null;
  dom_elements_min?: number | null;
  dom_interactive_max?: number | null;
  dom_interactive_mean?: number | null;
  dom_interactive_min?: number | null;
  domains?: Json | null;
  inp_latency_max?: number | null;
  inp_latency_mean?: number | null;
  inp_latency_min?: number | null;
  lab_cls_max?: number | null;
  lab_cls_mean?: number | null;
  lab_cls_min?: number | null;
  lab_contentsize?: number | null;
  lab_css_contentsize_max?: number | null;
  lab_css_contentsize_mean?: number | null;
  lab_css_contentsize_min?: number | null;
  lab_css_request_count_max?: number | null;
  lab_css_request_count_mean?: number | null;
  lab_css_request_count_min?: number | null;
  lab_css_transfersize_max?: number | null;
  lab_css_transfersize_mean?: number | null;
  lab_css_transfersize_min?: number | null;
  lab_domain_lookup?: number | null;
  lab_error_max?: number | null;
  lab_error_mean?: number | null;
  lab_error_min?: number | null;
  lab_fcp_max?: number | null;
  lab_fcp_mean?: number | null;
  lab_fcp_min?: number | null;
  lab_fid_max?: number | null;
  lab_fid_mean?: number | null;
  lab_fid_min?: number | null;
  lab_firstmeaningfulpaint_max?: number | null;
  lab_firstmeaningfulpaint_mean?: number | null;
  lab_firstmeaningfulpaint_min?: number | null;
  lab_font_contentsize_max?: number | null;
  lab_font_contentsize_mean?: number | null;
  lab_font_contentsize_min?: number | null;
  lab_font_request_count_max?: number | null;
  lab_font_request_count_mean?: number | null;
  lab_font_request_count_min?: number | null;
  lab_font_transfersize_max?: number | null;
  lab_font_transfersize_mean?: number | null;
  lab_font_transfersize_min?: number | null;
  lab_fullyloaded_max?: number | null;
  lab_fullyloaded_mean?: number | null;
  lab_fullyloaded_min?: number | null;
  lab_html_contentsize_max?: number | null;
  lab_html_contentsize_mean?: number | null;
  lab_html_contentsize_min?: number | null;
  lab_html_request_count_max?: number | null;
  lab_html_request_count_mean?: number | null;
  lab_html_request_count_min?: number | null;
  lab_html_transfersize_max?: number | null;
  lab_html_transfersize_mean?: number | null;
  lab_html_transfersize_min?: number | null;
  lab_image_contentsize_max?: number | null;
  lab_image_contentsize_mean?: number | null;
  lab_image_contentsize_min?: number | null;
  lab_image_request_count_max?: number | null;
  lab_image_request_count_mean?: number | null;
  lab_image_request_count_min?: number | null;
  lab_image_transfersize_max?: number | null;
  lab_image_transfersize_mean?: number | null;
  lab_image_transfersize_min?: number | null;
  lab_js_contentsize_max?: number | null;
  lab_js_contentsize_mean?: number | null;
  lab_js_contentsize_min?: number | null;
  lab_js_request_count_max?: number | null;
  lab_js_request_count_mean?: number | null;
  lab_js_request_count_min?: number | null;
  lab_js_transfersize_max?: number | null;
  lab_js_transfersize_mean?: number | null;
  lab_js_transfersize_min?: number | null;
  lab_json_contentsize_max?: number | null;
  lab_json_contentsize_mean?: number | null;
  lab_json_contentsize_min?: number | null;
  lab_json_request_count_max?: number | null;
  lab_json_request_count_mean?: number | null;
  lab_json_request_count_min?: number | null;
  lab_json_transfersize_max?: number | null;
  lab_json_transfersize_mean?: number | null;
  lab_json_transfersize_min?: number | null;
  lab_lcp_max?: number | null;
  lab_lcp_mean?: number | null;
  lab_lcp_min?: number | null;
  lab_speed_index_max?: number | null;
  lab_speed_index_mean?: number | null;
  lab_speed_index_min?: number | null;
  lab_srt_max?: number | null;
  lab_srt_mean?: number | null;
  lab_srt_min?: number | null;
  lab_svg_contentsize_max?: number | null;
  lab_svg_contentsize_mean?: number | null;
  lab_svg_contentsize_min?: number | null;
  lab_svg_request_count_max?: number | null;
  lab_svg_request_count_mean?: number | null;
  lab_svg_request_count_min?: number | null;
  lab_svg_transfersize_max?: number | null;
  lab_svg_transfersize_mean?: number | null;
  lab_svg_transfersize_min?: number | null;
  lab_tbt_max?: number | null;
  lab_tbt_mean?: number | null;
  lab_tbt_min?: number | null;
  lab_total_contentsize_max?: number | null;
  lab_total_contentsize_mean?: number | null;
  lab_total_contentsize_min?: number | null;
  lab_total_requests_max?: number | null;
  lab_total_requests_mean?: number | null;
  lab_total_requests_min?: number | null;
  lab_total_transfersize_max?: number | null;
  lab_total_transfersize_mean?: number | null;
  lab_total_transfersize_min?: number | null;
  lab_ttfb_max?: number | null;
  lab_ttfb_mean?: number | null;
  lab_ttfb_min?: number | null;
  lcp_element_size_max?: number | null;
  lcp_element_size_mean?: number | null;
  lcp_element_size_min?: number | null;
  longtaskcount?: number | null;
  page_address?: string;
  page_filmstrip?: string | null;
  page_loading_video_max?: string | null;
  page_loading_video_mean?: string | null;
  page_loading_video_min?: string | null;
  page_screenshot?: string | null;
  pageweight?: number | null;
  performance_score_max?: number | null;
  performance_score_mean?: number | null;
  performance_score_min?: number | null;
  record_id?: string;
  third_party_content_size_max?: number | null;
  third_party_content_size_mean?: number | null;
  third_party_content_size_min?: number | null;
  third_party_req_max?: number | null;
  third_party_req_mean?: number | null;
  third_party_req_min?: number | null;
  third_party_transfer_size_max?: number | null;
  third_party_transfer_size_mean?: number | null;
  third_party_transfer_size_min?: number | null;
  useragent?: string | null;
  windowsize?: string | null;
  lcp_data?: Json | null;
  blocking_scripts?: Json | null;
  lcp_timing?: Json | null;
  pageload_timing?: Json | null;
};

export type DataByDeviceType = {
  desktop: performance_data;
  mobile: performance_data;
  date: string;
};

export type PageData = {
  perf_data: DataByDeviceType[];
  url: string;
  imageDesktop?: string;
  imageMobile?: string;
  page_title?: string;
  desktopUserAgent?: string;
  mobileUserAgent?: string;
  windowSizeMobile?: string;
  windowSizeDesktop?: string;
};
