name: Daily Usage Update

on:
  schedule:
    - cron: "1 0 * * *" # Runs daily at 00:01 UTC
  workflow_dispatch:

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
      - name: Daily user usage update
        run: |
          curl -f -X POST https://analytics.speedy.site/api/subscriptions/usage \
            -H "Authorization: Bearer usagecountercronvalid" \
            -H "Content-Type: application/json"