name: Daily Usage Update

on:
  schedule:
    - cron: "1 0 * * *" # Runs daily at 00:01 UTC
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
      - name: User based usage update (daily)
        run: |
          curl -X POST https://speedy-sense.vercel.app/api/subscriptions/usage \
            -H "Authorization: Bearer usagecountercronvalid"
